# Generated by Django 3.2.3 on 2021-08-16 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_échéance', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_échéance', models.CharField(blank=True, max_length=255, null=True)),
                ('mois_échéance', models.DateField(blank=True, null=True)),
                ('semaine_échéance', models.IntegerField(blank=True, null=True)),
                ('date_debut_semaine', models.DateField(blank=True, null=True)),
                ('date_fin_semaine', models.DateField(blank=True, null=True)),
                ('montant_penalité', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_frequence', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_mise', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatutTontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_statut', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Suggession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TontineAdogbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tontine', models.CharField(blank=True, max_length=255, null=True)),
                ('sigle_tontine', models.CharField(blank=True, max_length=255, null=True)),
                ('annee_tontine', models.DateField(blank=True, null=True)),
                ('date_debut_tontine', models.DateField(blank=True, null=True)),
                ('date_fin_tontine', models.DateField(blank=True, null=True)),
                ('pénalité', models.BooleanField(default=True)),
                ('montant_penalité', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='postes_image/')),
                ('fréquence_paiement_tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.frequence')),
                ('statut_tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.statuttontine')),
            ],
        ),
        migrations.CreateModel(
            name='Temoignages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contain', models.TextField()),
                ('date_post', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_reçu', models.CharField(blank=True, max_length=255, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant_payé', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nom_adhérent', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nom_échéance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.echeance')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(blank=True, max_length=255, null=True)),
                ('prix_unitaire_produit', models.CharField(blank=True, max_length=255, null=True)),
                ('produit_liquide', models.BooleanField(default=True)),
                ('prix_litre_produit', models.CharField(blank=True, max_length=255, null=True)),
                ('categorie_produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.categorieproduit')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.categoriefournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_souscription', models.CharField(blank=True, max_length=255, null=True)),
                ('montant_souscription', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('opération_sucèss', models.BooleanField(blank=True, default=False, null=True)),
                ('avoir_payé', models.BooleanField(blank=True, default=False, null=True)),
                ('nom_adhérent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nom_échéance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.echeance')),
            ],
        ),
        migrations.CreateModel(
            name='Initiateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_initiateur', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_initiateur', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_initiateur', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_tel_initiateur', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_email_initiateur', models.CharField(blank=True, max_length=255, null=True)),
                ('email_de_notification', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_initiateur', models.ImageField(blank=True, null=True, upload_to='postes_image/')),
                ('nom_tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.tontineadogbe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeAdogbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_groupe', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_groupe', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_personne', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nom_tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.tontineadogbe')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=255)),
                ('prenom_fournisseur', models.CharField(max_length=255)),
                ('adresse_fournisseur', models.CharField(max_length=255)),
                ('numero_tel_fournisseur', models.CharField(max_length=255)),
                ('categorie_fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.categoriefournisseur')),
                ('nom_TontineAdogbe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.tontineadogbe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='echeance',
            name='mise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.mise'),
        ),
        migrations.CreateModel(
            name='AgentTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_identification_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('âge_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_tel_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_temoin_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_temoin_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('âge_temoin_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_temoin_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_tel_temoin_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_mail_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('email_de_notification', models.CharField(blank=True, max_length=255, null=True)),
                ('terme_contrat', models.ImageField(blank=True, null=True, upload_to='postes_image/')),
                ('photo_adhérent', models.ImageField(blank=True, null=True, upload_to='postes_image/')),
                ('salaire_agent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nom_tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.tontineadogbe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_identification_adhérent', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_adhérent', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_adhérent', models.CharField(blank=True, max_length=255, null=True)),
                ('âge_adhérent', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_adhérent', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_tel_adhérent', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_mail_adhérent', models.CharField(blank=True, max_length=255, null=True)),
                ('email_de_notification', models.CharField(blank=True, max_length=255, null=True)),
                ('Avoir_agent_terrain', models.BooleanField(default=True)),
                ('photo_adhérent', models.ImageField(blank=True, null=True, upload_to='postes_image/')),
                ('nom_agent_terrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.agentterrain')),
                ('nom_groupe_tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.groupeadogbe')),
                ('nom_tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.tontineadogbe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
