# Generated by Django 3.2.3 on 2021-08-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tontineadogbe',
            name='annee_tontine',
        ),
    ]
