# Generated by Django 3.2.3 on 2021-08-16 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0002_remove_tontineadogbe_annee_tontine'),
    ]

    operations = [
        migrations.AddField(
            model_name='tontineadogbe',
            name='annee_tontine',
            field=models.PositiveIntegerField(default=2020, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
