# Generated by Django 3.2.3 on 2021-08-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0003_tontineadogbe_annee_tontine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequence',
            name='nom_frequence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mise',
            name='montant_mise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
