# Generated by Django 3.2.3 on 2021-08-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0005_auto_20210820_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='adresse_mail_adhérent',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='nom_adhérent',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='prenom_adhérent',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='nom_fournisseur',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='prenom_fournisseur',
        ),
        migrations.RemoveField(
            model_name='initiateur',
            name='adresse_email_initiateur',
        ),
        migrations.RemoveField(
            model_name='initiateur',
            name='nom_initiateur',
        ),
        migrations.RemoveField(
            model_name='initiateur',
            name='prenom_initiateur',
        ),
    ]
