# Generated by Django 3.2.3 on 2021-08-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0006_auto_20210821_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentterrain',
            old_name='photo_adhérent',
            new_name='photo_agent',
        ),
        migrations.RemoveField(
            model_name='agentterrain',
            name='nom_agent',
        ),
        migrations.RemoveField(
            model_name='agentterrain',
            name='prenom_agent',
        ),
        migrations.AlterField(
            model_name='adherent',
            name='âge_adhérent',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentterrain',
            name='âge_agent',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mise',
            name='montant_mise',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
