# Generated by Django 3.2.3 on 2021-08-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0007_auto_20210824_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='âge_adhérent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mise',
            name='montant_mise',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
