# Generated by Django 3.2.3 on 2021-08-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0008_auto_20210824_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentterrain',
            name='âge_agent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
