# Generated by Django 3.2.3 on 2021-08-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0009_alter_agentterrain_âge_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentterrain',
            name='salaire_agent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='echeance',
            name='montant_penalité',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='groupeadogbe',
            name='nombre_personne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='recu',
            name='montant_payé',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
