# Generated by Django 3.2.3 on 2021-08-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0011_alter_agentterrain_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adherent',
            options={'permissions': (('can_mark_user_adhérent', 'Set user as adhérent'),)},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'permissions': (('can_mark_user_fournisseur', 'Set user as initiateur'),)},
        ),
        migrations.AlterModelOptions(
            name='initiateur',
            options={'permissions': (('can_mark_user_initiateur', 'Set user as initiateur'),)},
        ),
    ]
