# Generated by Django 3.2.3 on 2021-08-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0012_auto_20210824_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'permissions': (('can_mark_user_fournisseur', 'Set user as fournisseur'),)},
        ),
    ]
