# Generated by Django 3.2.3 on 2021-08-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0013_alter_fournisseur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={},
        ),
    ]
