# Generated by Django 3.2.3 on 2021-08-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0014_alter_fournisseur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'permissions': (('can_mark_user_fournisseur', 'Set user as fournisseurproduit'),)},
        ),
    ]
