# Generated by Django 3.2.3 on 2021-08-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0015_alter_fournisseur_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echeance',
            name='mise',
        ),
        migrations.AddField(
            model_name='echeance',
            name='nom_groupe_tontine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.groupeadogbe'),
        ),
        migrations.AddField(
            model_name='groupeadogbe',
            name='mise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.DeleteModel(
            name='Mise',
        ),
    ]
