# Generated by Django 3.2.3 on 2021-08-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0016_auto_20210826_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriefournisseur',
            name='nom_Tontine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.tontineadogbe'),
        ),
        migrations.AddField(
            model_name='categorieproduit',
            name='nom_Tontine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.tontineadogbe'),
        ),
        migrations.AddField(
            model_name='frequence',
            name='nom_Tontine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.tontineadogbe'),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_Tontine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.tontineadogbe'),
        ),
    ]
