# Generated by Django 3.2.3 on 2021-08-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0017_auto_20210829_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriefournisseur',
            old_name='nom_Tontine',
            new_name='nom_tontine',
        ),
        migrations.RenameField(
            model_name='categorieproduit',
            old_name='nom_Tontine',
            new_name='nom_tontine',
        ),
        migrations.RenameField(
            model_name='frequence',
            old_name='nom_Tontine',
            new_name='nom_tontine',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='nom_Tontine',
            new_name='nom_tontine',
        ),
    ]
