# Generated by Django 3.2.3 on 2021-09-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0018_auto_20210829_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeadogbe',
            name='nature_produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.produit'),
        ),
    ]
