# Generated by Django 3.2.3 on 2021-09-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0019_groupeadogbe_nature_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie_fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.categoriefournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.fournisseur'),
        ),
    ]
