# Generated by Django 3.2.3 on 2021-09-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0021_auto_20210927_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echeance_jour',
            name='mois_échéance',
        ),
    ]
