# Generated by Django 3.2.3 on 2021-09-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0022_remove_echeance_jour_mois_échéance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mois', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='echeance_jour',
            name='payer_oui',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='echeance_mois',
            name='payer_oui',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='echeance_semaine',
            name='payer_oui',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='echeance_jour',
            name='nom_mois',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.mois'),
        ),
        migrations.AlterField(
            model_name='echeance_mois',
            name='nom_mois',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.mois'),
        ),
        migrations.AlterField(
            model_name='echeance_semaine',
            name='nom_mois',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.mois'),
        ),
        migrations.AlterField(
            model_name='groupeadogbe',
            name='nom_mois',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.mois'),
        ),
    ]
