# Generated by Django 3.2.3 on 2021-09-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0023_auto_20210927_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echeance_jour',
            name='nom_mois',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='echeance_jour',
            name='payer_oui',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='echeance_mois',
            name='nom_mois',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='echeance_mois',
            name='payer_oui',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='echeance_semaine',
            name='nom_mois',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='echeance_semaine',
            name='payer_oui',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupeadogbe',
            name='nom_mois',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Mois',
        ),
    ]
