# Generated by Django 3.2.3 on 2021-09-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0024_auto_20210927_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mois', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='echeance_jour',
            name='nom_mois',
        ),
        migrations.RemoveField(
            model_name='echeance_mois',
            name='nom_mois',
        ),
        migrations.RemoveField(
            model_name='echeance_semaine',
            name='nom_mois',
        ),
        migrations.RemoveField(
            model_name='groupeadogbe',
            name='nom_mois',
        ),
        migrations.AddField(
            model_name='echeance_jour',
            name='mois_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.mois'),
        ),
        migrations.AddField(
            model_name='echeance_mois',
            name='mois_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.mois'),
        ),
        migrations.AddField(
            model_name='echeance_semaine',
            name='mois_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.mois'),
        ),
        migrations.AddField(
            model_name='groupeadogbe',
            name='mois_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.mois'),
        ),
    ]
