# Generated by Django 3.2.3 on 2021-09-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0025_auto_20210927_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echeance_jour',
            name='payer_oui',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='echeance_mois',
            name='payer_oui',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='echeance_semaine',
            name='payer_oui',
            field=models.BooleanField(default=False),
        ),
    ]
