# Generated by Django 3.2.3 on 2021-09-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0026_auto_20210927_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeance_jour',
            name='numero_jour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
