# Generated by Django 3.2.3 on 2021-09-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0030_alter_carnet_adhérent'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='date_adhésion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adherent',
            name='profession_adhérent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
