# Generated by Django 3.2.3 on 2021-09-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0031_auto_20210929_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupeadogbe',
            name='mois_name',
        ),
    ]
