# Generated by Django 3.2.3 on 2021-09-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0032_remove_groupeadogbe_mois_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adherent',
            options={'permissions': [('can_mark_user_adhérent', 'Set user as adhérent'), ('can_mark_adhérent_subscribe_échéance_jour', 'Set user as adhérent_subscribe_échéance_jour'), ('can_mark_adhérent_subscribe_échéance_semaine', 'Set user as adhérent_subscribe_échéance_semaine'), ('can_mark_adhérent_subscribe_échéance_mois', 'Set user as adhérent_subscribe_échéance_mois')]},
        ),
    ]
