# Generated by Django 3.2.3 on 2021-10-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0037_alter_adherent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_echeance_semaine',
            name='numero_semaine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.echeance_semaine'),
        ),
    ]
