# Generated by Django 3.2.3 on 2022-02-12 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eadogbeapp', '0039_auto_20211007_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiche_journalière',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fiche', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_jour', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement_mise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mise', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Fiche_journalière', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.fiche_journalière')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_secretaire', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_tel_secretaire', models.CharField(blank=True, max_length=255, null=True)),
                ('email_de_notification', models.EmailField(blank=True, max_length=255, null=True)),
                ('photo_secretaire', models.ImageField(blank=True, null=True, upload_to='postes_image/')),
            ],
            options={
                'permissions': (('can_mark_user_secretaire', 'Set user as secretaire'),),
            },
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_semaine', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorieproduit',
            name='nom_tontine',
        ),
        migrations.RemoveField(
            model_name='echeance_jour',
            name='mois_name',
        ),
        migrations.RemoveField(
            model_name='echeance_mois',
            name='mois_name',
        ),
        migrations.RemoveField(
            model_name='echeance_semaine',
            name='mois_name',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='categorie_fournisseur',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='nom_TontineAdogbe',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='user',
        ),
        migrations.RemoveField(
            model_name='frequence',
            name='nom_tontine',
        ),
        migrations.RemoveField(
            model_name='groupeadogbe',
            name='fréquence_paiement_tontine',
        ),
        migrations.RemoveField(
            model_name='groupeadogbe',
            name='nature_produit',
        ),
        migrations.RemoveField(
            model_name='groupeadogbe',
            name='nom_tontine',
        ),
        migrations.RemoveField(
            model_name='paiement_echeance_jour',
            name='jour',
        ),
        migrations.RemoveField(
            model_name='paiement_echeance_jour',
            name='nom_adhérent',
        ),
        migrations.RemoveField(
            model_name='paiement_echeance_mois',
            name='nom_adhérent',
        ),
        migrations.RemoveField(
            model_name='paiement_echeance_mois',
            name='numero_mois',
        ),
        migrations.RemoveField(
            model_name='paiement_echeance_semaine',
            name='nom_adhérent',
        ),
        migrations.RemoveField(
            model_name='paiement_echeance_semaine',
            name='numero_semaine',
        ),
        migrations.RemoveField(
            model_name='penaliteuserjour',
            name='adhérent',
        ),
        migrations.RemoveField(
            model_name='penaliteuserjour',
            name='jour',
        ),
        migrations.RemoveField(
            model_name='penaliteusermois',
            name='adhérent',
        ),
        migrations.RemoveField(
            model_name='penaliteusermois',
            name='mois',
        ),
        migrations.RemoveField(
            model_name='penaliteusersemaine',
            name='adhérent',
        ),
        migrations.RemoveField(
            model_name='penaliteusersemaine',
            name='mois',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='prix_litre_produit',
            new_name='prix_mise_produit',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='Avoir_agent_terrain',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='nom_groupe_tontine',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie_fournisseur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie_produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix_unitaire_produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='produit_liquide',
        ),
        migrations.RemoveField(
            model_name='tontineadogbe',
            name='annee_tontine',
        ),
        migrations.RemoveField(
            model_name='tontineadogbe',
            name='date_debut_tontine',
        ),
        migrations.RemoveField(
            model_name='tontineadogbe',
            name='date_fin_tontine',
        ),
        migrations.RemoveField(
            model_name='tontineadogbe',
            name='montant_penalité',
        ),
        migrations.RemoveField(
            model_name='tontineadogbe',
            name='pénalité',
        ),
        migrations.RemoveField(
            model_name='tontineadogbe',
            name='statut_tontine',
        ),
        migrations.AlterField(
            model_name='mois',
            name='nom_mois',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CategorieFournisseur',
        ),
        migrations.DeleteModel(
            name='CategorieProduit',
        ),
        migrations.DeleteModel(
            name='Echeance_jour',
        ),
        migrations.DeleteModel(
            name='Echeance_mois',
        ),
        migrations.DeleteModel(
            name='Echeance_semaine',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
        migrations.DeleteModel(
            name='Frequence',
        ),
        migrations.DeleteModel(
            name='GroupeAdogbe',
        ),
        migrations.DeleteModel(
            name='Paiement_echeance_jour',
        ),
        migrations.DeleteModel(
            name='Paiement_echeance_mois',
        ),
        migrations.DeleteModel(
            name='Paiement_echeance_semaine',
        ),
        migrations.DeleteModel(
            name='PenaliteUserJour',
        ),
        migrations.DeleteModel(
            name='PenaliteUserMois',
        ),
        migrations.DeleteModel(
            name='PenaliteUserSemaine',
        ),
        migrations.DeleteModel(
            name='StatutTontine',
        ),
        migrations.AddField(
            model_name='secretaire',
            name='nom_tontine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.tontineadogbe'),
        ),
        migrations.AddField(
            model_name='secretaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement_mise',
            name='mois',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.mois'),
        ),
        migrations.AddField(
            model_name='paiement_mise',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.jours'),
        ),
        migrations.AddField(
            model_name='paiement_mise',
            name='nom_adhérent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement_mise',
            name='num_carnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadogbeapp.carnet'),
        ),
        migrations.AddField(
            model_name='paiement_mise',
            name='objectif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.produit'),
        ),
        migrations.AddField(
            model_name='fiche_journalière',
            name='mois',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.mois'),
        ),
        migrations.AddField(
            model_name='fiche_journalière',
            name='semaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.semaine'),
        ),
    ]
