# Generated by Django 3.2.3 on 2022-02-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0041_alter_produit_prix_mise_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche_journalière',
            name='numero_fiche',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
