# Generated by Django 3.2.3 on 2022-02-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0042_alter_fiche_journalière_numero_fiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semaine',
            name='num_semaine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
