# Generated by Django 3.2.3 on 2022-02-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0044_alter_paiement_mise_nom_adhérent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_mise',
            name='nom_adhérent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadogbeapp.adherent'),
        ),
    ]
