# Generated by Django 3.2.3 on 2022-02-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0047_mise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mise',
            name='agent',
        ),
    ]
