# Generated by Django 3.2.3 on 2022-02-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0049_niveau'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mise',
        ),
    ]
