# Generated by Django 3.2.3 on 2022-02-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0050_delete_mise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mise_adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.niveau')),
                ('nom_adhérent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadogbeapp.adherent')),
                ('nom_agent_terrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.agentterrain')),
            ],
        ),
    ]
