# Generated by Django 3.2.3 on 2022-02-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0051_mise_adherent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mise_adherent',
            name='valider',
            field=models.BooleanField(default=False),
        ),
    ]
