# Generated by Django 3.2.3 on 2022-02-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0052_mise_adherent_valider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mois_adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_mois', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
