# Generated by Django 3.2.3 on 2022-02-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0055_niveau_mois_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_mise',
            name='num_carnet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
