# Generated by Django 3.2.3 on 2022-02-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0056_alter_paiement_mise_num_carnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_mise',
            name='montant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
