# Generated by Django 3.2.3 on 2022-03-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0057_alter_paiement_mise_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mois',
            name='nom_mois',
        ),
        migrations.AddField(
            model_name='mois',
            name='num_mois',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
