# Generated by Django 3.2.3 on 2022-03-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0059_auto_20220305_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte_finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_carnet', models.CharField(blank=True, max_length=255, null=True)),
                ('mise', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('finish', models.BooleanField(default=False)),
                ('date_adhésion', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('nom_adhérent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadogbeapp.adherent')),
                ('objectif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.produit')),
            ],
        ),
    ]
