# Generated by Django 3.2.3 on 2022-03-10 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eadogbeapp', '0060_carte_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnet',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carnet',
            name='objectif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eadogbeapp.produit'),
        ),
        migrations.AlterField(
            model_name='carnet',
            name='adhérent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eadogbeapp.adherent'),
        ),
    ]
