# Generated by Django 3.2.3 on 2022-03-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0063_carnet_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carnet',
            old_name='agent',
            new_name='agentt',
        ),
    ]
