# Generated by Django 3.2.3 on 2022-03-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0064_rename_agent_carnet_agentt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='agentt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadogbeapp.agentterrain'),
        ),
    ]
