# Generated by Django 3.2.3 on 2022-03-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadogbeapp', '0065_alter_carnet_agentt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche_journalière',
            name='numero_fiche',
        ),
    ]
